### ISSUE TITLE
Console is flooded with "HUD update"

### ISSUE THREAD

**Issue by Wolfcl0ck** [elishmel/LCExtendedHUD#1]
This is a nice mod, but it becomes IMPOSSIBLE to check for issues with the mod constantly spamming the log/console with "HUD update." Could this be removed in an update, please?

**Comment by elishmel** [comment]
Hello and thank you for bringing this to my attention.

I will remove this log as soon as I get to my workstation (should be tomorrow) and introduce better debug handling in general.

**Comment by elishmel** [comment]
Hello again!

I've fixed the issue here a85f585 and uploaded the updated mod to the Thunderstore webpage.
